GPSMap/Controllers/EricssonUploadController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using GPSDB;
using System.Web;
using System.IO;
using GPSMap.Models;
using System.Xml;
using System.Data;
using OfficeOpenXml;
using GPSMap.Data;

namespace GPSMap.Controllers
{
    public class EricssonUploadController : BaseController
    {
        // GET: EricssonUpload
        public ActionResult Index()
        {
            if (this.hasRights("PM Counter"))
            {
                return View();
            }
            else
            {
                return Redirect("/Account/NotAuthorised");
            }
        }


        [HttpPost]
        public ActionResult Index(HttpPostedFileBase[] file)
        {
            List<string> xmlfilename = new List<string>();
            string excelfilename = "";
            foreach (HttpPostedFileBase ff in file)
            {
                if (ff.ContentLength > 0)
                {
                    var allowedExtensions = new[] { ".xml", ".xlsx", ".xlsm" };
                    var extension = Path.GetExtension(ff.FileName);
                    if (!allowedExtensions.Contains(extension))
                    {
                        ViewBag.UploadStatus = "InvalidFileType";
                        return View();
                    }

                    var fileName = Path.GetFileName(ff.FileName);
                    var path = Path.Combine(Server.MapPath("~/EricosnUpload"), fileName);

                    if (!System.IO.Directory.Exists(Path.Combine(Server.MapPath("~/EricosnUpload"))))
                    {
                        System.IO.Directory.CreateDirectory(Path.Combine(Server.MapPath("~/EricosnUpload")));
                    }

                    if (System.IO.File.Exists(path))
                    {
                        System.IO.File.Delete(path);
                    }

                    if (!System.IO.File.Exists(path))
                    {
                        ff.SaveAs(path);
                        if (extension == ".xml")
                        {
                            xmlfilename.Add(path);

                        }
                        else
                        {
                            excelfilename = path;
                        }
                    }


                    ViewBag.UploadStatus = "Success";
                }
                else
                {
                    ViewBag.UploadStatus = "Failed";
                }

            }


            foreach (string abcfilename in xmlfilename)
            {
                ReadXMLEricsson(abcfilename);
            }

            return View();
        }


        private void ReadXMLEricsson(string FN)
        {
            try
            {

                var path = Path.Combine(Server.MapPath("~/EricosnUpload"), "Parameters.xlsx");


                DataTable data = ReadDataFromParameterExcel(path, "EricssonGVP");

                var ImpValue = data.AsEnumerable()
              .Select(dataRow => new EricssonGV
              {
                  MOC = dataRow.Field<string>("MOC"),
                  PN = dataRow.Field<string>("Parameter_Name")

              }).ToList();





                XmlDocument doc = new XmlDocument();
                xmlDataRawEricsson XMLEricsson = new xmlDataRawEricsson();
                XMLEricsson.xmlDataEricsson = null;
                XMLEricsson.xmlDataEricsson = new List<ericssonxmldetail>();

                doc.Load(FN);
                XmlNodeList SubNetWorkList = doc.GetElementsByTagName("xn:SubNetwork");

                foreach (XmlNode objSubNetWork in SubNetWorkList)
                {
                    if (objSubNetWork.ParentNode.Name != "xn:SubNetwork")
                    {

                    }
                    else
                    {

                        string subnetwork = objSubNetWork.Attributes["id"].InnerText;

                        SubNetWorkList = null;
                        XmlDocument docManagedElement = new XmlDocument();
                        docManagedElement.LoadXml(objSubNetWork.InnerXml);

                        XmlNodeList MElement = docManagedElement.GetElementsByTagName("xn:ManagedElement");
                        string ManagedElement = MElement[0].Attributes["id"].InnerText;
                        string MEContext = "";
                        foreach (XmlNode nodeME in MElement[0].ChildNodes)
                        {

                            if (nodeME.Name == "xn:attributes")
                            {
                                MEContext = nodeME.FirstChild.InnerText;
                            }
                            else if (nodeME.Name == "xn:VsDataContainer")
                            {
                                ///Code
                                readdatacontainernode(nodeME, ImpValue, FN, subnetwork, MEContext, ref XMLEricsson);

                                ///Code End



                            }

                        }


                    }
                }






                //var queryT = (from left in XMLEricsson.xmlDataEricsson
                //              join right in ImpValue on new { p1 = left.Paramenter.ToString().Trim().ToUpper() } equals new { p1 = right.PN.ToString().Trim().ToUpper() } into joinedList
                //              from sub in joinedList.DefaultIfEmpty()
                //              select new listItemEricsson
                //              {
                //                  SubNetwork = left.SubNetwork,
                //                  ManagedElement = left.ManagedElement,
                //                  Cell = left.Cell,
                //                  Paramenter = left.Paramenter,
                //                  Schedule = left.Schedule,
                //                  Discrepancy = "",
                //                  GUIValue = sub == null ? "NULL" : "",
                //                  Value = left.Value

                //              }).ToList();


                //var queryT2 = queryT.Where(x => x.GUIValue != "NULL").Select(m => new listItemEricsson
                //{

                //    SubNetwork = m.SubNetwork,
                //    ManagedElement = m.ManagedElement,
                //    Cell = m.Cell,
                //    Paramenter = m.Paramenter,
                //    Schedule = m.Schedule,
                //    Discrepancy = ReturnDesp(m.Value, m.GUIValue),
                //    GUIValue = m.GUIValue,
                //    Value = m.Value

                //}).ToList();






            }
            catch (Exception ex)
            {

            }
        }

        private void readdatacontainernode(XmlNode nodeME, List<EricssonGV> ImpValue, string FN, string subnetwork, string MEContext, ref xmlDataRawEricsson xmlfiledata)
        {
            try
            {
                string Cell = nodeME.Attributes["id"].InnerText;
                int countmoc = 0;
                string tempmoc = "";
                string originalmoc = "";
                foreach (XmlNode parameterlist1 in nodeME.ChildNodes)
                {

                    if (parameterlist1.Name.Contains("attributes"))
                    {
                        foreach (XmlNode parameterlist in parameterlist1.ChildNodes)
                        {
                            if (parameterlist.Name == "xn:vsDataFormatVersion")
                            {
                                continue;
                            }
                            else if (parameterlist.Name == "xn:vsDataType")
                            {
                                originalmoc = tempmoc = parameterlist.FirstChild.Value;
                                tempmoc = tempmoc.Replace("vsData", "").ToUpper().Trim();

                                countmoc = ImpValue.Where(x => x.MOC.ToUpper().Trim().ToString() == tempmoc).Count();

                                continue;

                            }
                            if (parameterlist.Name.Contains(originalmoc))
                            {
                                if (countmoc == 0)
                                {
                                    continue;
                                }


                                foreach (XmlNode parameter in parameterlist.ChildNodes)
                                {
                                    if (!parameter.HasChildNodes)
                                    {

                                        string parametername = parameter.Name.Contains(':') == true ? parameter.Name.Split(':')[1].ToString() : parameter.Name;
                                        if (ImpValue.Where(x => x.PN.ToUpper().Trim().ToString() == parametername.ToUpper().Trim()).Count() == 0)
                                        {
                                            continue;
                                        }

                                        ericssonxmldetail obj;
                                        if (parametername == "UeMeasControlID")
                                        {

                                            obj = new ericssonxmldetail
                                            {

                                                SubNetwork = subnetwork,
                                                DataContainer = Cell,
                                                MeContext = MEContext,
                                                UeMeasControlId = parameter.InnerText,
                                                MOC = tempmoc,
                                                Parameter = parametername,
                                                Value = parameter.InnerText,
                                                Discrepency = "",
                                                GUIValue = "",
                                                Schedule = ""

GPSMap/Views/EricssonUpload/Index.cshtml
@{
    /**/

    ViewBag.Title = "Ericsson Files Upload";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="panel panel-default">
    <div class="panel-heading">Import Map Records</div>
    <div class="panel-body">
        @using (Html.BeginForm("Index", "EricssonUpload", FormMethod.Post, new { @class = "form-horizontal", enctype = "multipart/form-data" }))
        {
            @section scripts
                {
                @if (ViewBag.UploadStatus != null)
                {
                    if (ViewBag.UploadStatus == "Success")
                    {
                        <script>
                            $(document).ready(function () {
                                toastr.success('File records are imported successfully.');
                            });
                        </script>
                    }
                    else if (ViewBag.UploadStatus == "InvalidFileType")
                    {
                        <script>
                            $(document).ready(function () {
                                toastr.error('Invalid File Type. Please upload only *.xml, excel files.');
                            });
                        </script>
                    }
                    else
                    {
                        <script>
                            $(document).ready(function () {
                                toastr.error('Error! File records are not imported.');
                            });
                        </script>
                    }
                }
            }
            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 control-label"></label>

            </div>
            <div class="form-group">
                <label for="inputPassword3" class="col-sm-2 control-label">Upload your xml file</label>
                <div class="col-sm-10">
                    <input type="file" class="form-control" id="file" multiple="multiple" name="file" accept=".xml">
                </div>
            </div>
            <div class="form-group">
                <label for="inputPassword3" class="col-sm-2 control-label">Upload your xlsm file</label>
                <div class="col-sm-10">
                    <input type="file" class="form-control"  id="file" name="file" accept=".xlsm">
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-default">Upload File</button>
                </div>
            </div>
        }
    </div>
</div>