GPSMap/Controllers/EricssonController.cs
using GPSDB;
using GPSMap.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Web.Mvc;

namespace GPSMap.Controllers
{


    [Authorize]
    public class EricssonController : BaseController
    {
        public List<GPSDB.ericsson_5gdetail> p_ericsson_5gdetail { get; set; }
        // GET: Ericsson
        public ActionResult Index()
        {
            if (this.hasRights("OSS Reporting") || this.hasRights("PM Counter"))
            {
                return View();
            }
            else
            {
                return Redirect("/Account/NotAuthorised");
            }
        }
        [HttpPost]
        [MultipleButton(Name = "action", Argument = "Index")]
        public ActionResult Index(Ericsson5gXMLSearch form)
        {

            using (var dbContext = new DatabaseContext())
            {
                // var mst = dbContext.ericsson_5gmaster.AsQueryable();
                var dtl = dbContext.ericsson_5gdetail.AsQueryable();

                if (form.ToDate != null)
                {
                    dtl = dtl.Where(t => t.CreatedDate <= form.ToDate.Value);
                }
                if (form.FromDate != null)
                {
                    dtl = dtl.Where(t => t.CreatedDate >= form.FromDate.Value);
                }
                if (form.MOClass != null)
                {
                    dtl = dtl.Where(t => t.MOClass.Contains(form.MOClass));
                }
                if (form.ManagedElement != null)
                {
                    dtl = dtl.Where(t => t.ManagedElement.Contains(form.ManagedElement));
                }
                if (form.counter != null)
                {
                    dtl = dtl.Where(t => t.counter.Contains(form.counter));
                }
                var filterd = dtl.ToList().Take(5000);

                ViewBag.map = filterd;
                p_ericsson_5gdetail = dtl.ToList();


            }

            return View(form);
        }

        public ActionResult Dashboard()
        {
            var chart = new KPIChartDataModel();
            using (var dbContext = new DatabaseContext())
            {
                chart.KPIValues = new SelectList(dbContext.kpimaster.Take(15).ToList().Select(n => new SelectListItem
                {
                    Text = n.KPIName,
                    Value = n.KPIId.ToString()
                }), "Value", "Text");
                var chartSearch = new ChartSearchModel();
                chart.SearchModel = chartSearch;
            }

            return View(chart);
        }

        public List<int> GetDays(int year, int month)
        {
            return Enumerable.Range(1, DateTime.DaysInMonth(year, month))
                             // Days: 1, 2 ... 31 etc.
                             .Select(day => new DateTime(year, month, day).Day)
                             // Map each day to a date
                             .ToList(); // Load dates into a list
        }

        public JsonResult GetChartData(ChartRequest request)
        {
            var KPIValues = new List<ChartKPIValues>();
            using (var dbContext = new DatabaseContext())
            {
                // var kpiName = request.KPIName;
                // var kpiName = "RACH Preamble Response Success Rate";
                // X PLMN KPI = SUM(X KPI Nem, for all the day for all the meneged elements)/ 
                // SUM(Den of X KPI of all the day for all the managed elements) ;

                if (request.KpiId != null && request.KpiId.Length > 0)
                {
                    foreach (var id in request.KpiId)
                    {
                        var records = dbContext.ericsson_kpi_data.Where(k => k.KPIId == id && k.ManagedElement == k.ManagedElement).ToList();
                        var KPI = new ChartKPIValues();
                        var chartValues = new ChartValues();

                        chartValues.ChartData = new List<string>();
                        var date = System.DateTime.Now;
                        if (request.Date != null)
                        {
                            date = Convert.ToDateTime(request.Date);
                        }

                        chartValues.Labels = new List<string>();
                        if (request.Trend == "Monthly")
                        {
                            //var daysOfMonth = this.GetDays(date.Year, date.Month);
                            //var recordquery = from r in records
                            //                  group r by new
                            //                  {
                            //                      r.CreatedDate.Day,
                            //                      r.CreatedDate.Month,
                            //                      r.CreatedDate.Year,
                            //                  } into gcs
                            //                  select new 
                            //                  {
                            //                      Day = gcs.Key.Day,
                            //                      Numerator = gcs.Sum(x=>x.Numerator),
                            //                      Denominator = gcs.Sum(x=>x.Denominator)
                            //                  };

                            //var dsd = recordquery.ToList();
                            //var finallist = (from d in daysOfMonth
                            //                join rq in recordquery on d equals rq.Day into gj
                            //                from days in gj.DefaultIfEmpty()
                            //                select new {
                            //                    Day = d,
                            //                    KPIValue = days?.Denominator != null && days?.Denominator > 0 ? days?.Numerator / days?.Denominator : days?.Numerator
                            //                }).ToList();
                            //var dd = finallist;
                            foreach (var item in this.GetDays(date.Year, date.Month))
                            {

                                if (!string.IsNullOrEmpty(Convert.ToString(item)))
                                {
                                    var dayRecord = records.Where(g => g.CreatedDate.Day == item && g.CreatedDate.Month == date.Month);
                                    var numeratorSum = 0M;
                                    var denominatorSum = 0M;
                                    var dayKPIValue = numeratorSum;
                                    if (dayRecord.Any())
                                    {
                                        numeratorSum = dayRecord.Sum(s => s.Numerator);
                                        denominatorSum = dayRecord.Sum(s => s.Denominator);
                                        if (denominatorSum > 0)
                                        {
                                            dayKPIValue = numeratorSum / denominatorSum;
                                        }
                                    }

                                    chartValues.ChartData.Add(dayKPIValue.ToString());
                                    chartValues.Labels.Add(string.Format("{0}/{1}/{2}", date.Year, date.Month.ToString("00"), item.ToString("00")));
                                }
                            }
                        }
                        else
                        {
                            // chartValues.Labels = System.Globalization.CultureInfo.CurrentCulture.DateTimeFormat.MonthNames.ToList();
                            for (var i = 0; i <= 23; i++)
                            {
                                // var dayValue = records.Where(g => DateTime.ParseExact(g.CreatedDate, "dd-MM-yyyy", CultureInfo.InvariantCulture).Month == i).Sum(s => s.KPIValue.ToDecimal());
                                var hourRecord = records.Where(g => g.CreatedDate.Hour == i);
                                var numeratorSum = 0M;
                                var denominatorSum = 0M;
                                var hourKPIValue = numeratorSum;
                                if (hourRecord.Any())
                                {
                                    numeratorSum = hourRecord.Sum(s => s.Numerator);
                                    denominatorSum = hourRecord.Sum(s => s.Denominator);
                                    if (denominatorSum > 0)
                                    {
                                        hourKPIValue = numeratorSum / denominatorSum;
                                    }
                                }
                                chartValues.Labels.Add(i.ToString());
                                chartValues.ChartData.Add(hourKPIValue.ToString());
                            }
                        }


                        KPI.KPI = dbContext.kpimaster.FirstOrDefault(s => s.KPIId == id).KPIName;
                        KPI.ChartData = chartValues;
                        KPIValues.Add(KPI);
                    }
                }
            }
            return Json(KPIValues, JsonRequestBehavior.AllowGet);
        }



        [HttpPost]
        [MultipleButton(Name = "action", Argument = "ExportCSV")]
        public FileResult ExportCSV(Ericsson5gXMLSearch form)
        {


            using (var dbContext = new DatabaseContext())
            {
                var dtl = dbContext.ericsson_5gdetail.AsQueryable();

                if (form.ToDate != null)
                {
                    dtl = dtl.Where(t => t.CreatedDate <= form.ToDate.Value);
                }
                if (form.FromDate != null)
                {
                    dtl = dtl.Where(t => t.CreatedDate >= form.FromDate.Value);
                }
                if (form.MOClass != null)
                {

GPSMap/Controllers/UploadController.cs
using GPSMap.Helper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Newtonsoft.Json;
using System.Text;
using GPSDB;
using System.Web;
using System.IO;
using NMFReaderForGPS;
using GPSMap.Parser;
using GPSMap.Models;

namespace GPSMap.Controllers
{
    [Authorize]
    public class UploadController : BaseController
    {
        // GET: Upload
        public ActionResult Index()
        {
            if (base.hasRights("Network Audit"))
            {
                return View();
            }
            else
            {
                return Redirect("/Account/NotAuthorised");
            }
        }

        [HttpPost]
        public ActionResult Index(HttpPostedFileBase file)
        {
            if (file.ContentLength > 0)
            {
                var allowedExtensions = new[] { ".nmf" };
                var extension = Path.GetExtension(file.FileName);
                if (!allowedExtensions.Contains(extension))
                {
                    ViewBag.UploadStatus = "InvalidFileType";
                    return View();
                }

                var fileName = Path.GetFileName(file.FileName);
                var path = Path.Combine(Server.MapPath("~/App_Data/uploads"), fileName);

                if (!System.IO.Directory.Exists(Path.Combine(Server.MapPath("~/App_Data/uploads"))))
                {
                    System.IO.Directory.CreateDirectory(Path.Combine(Server.MapPath("~/App_Data/uploads")));
                }

                if (!System.IO.File.Exists(path))
                {
                    file.SaveAs(path);
                }

                var nmfParser = new NMFParser();
                nmfParser.filePath = path;
                var attribute = nmfParser.ParseAttributes();
                var attributeId = SaveAttributes(attribute);
                Program.ReadNMLFile(path, attributeId);
                ViewBag.UploadStatus = "Success";
            }
            else
            {
                ViewBag.UploadStatus = "Failed";
            }

            return View();
        }

        private int SaveAttributes(MapAttributesModel model)
        {
            using (var dbContext = new DatabaseContext())
            {
                var mapAttributes = new MapAttributes();
                mapAttributes.name = model.Name;
                mapAttributes.imei = model.IMEI;
                mapAttributes.imsi = model.IMSI;
                mapAttributes.ue_label = model.Ue_Label;
                mapAttributes.ue_name = model.Ue_Name;
                mapAttributes.class_id = model.ClassId;
                dbContext.MapAttributes.Add(mapAttributes);
                dbContext.SaveChanges();

                return mapAttributes.attributeid;
            }
        }
    }
}

GPSMap/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Scripts.Render("~/bundles/modernizr")
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" />
    <link href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap.min.css" rel="stylesheet" />
    <link href="https://cdn.datatables.net/autofill/2.3.4/css/autoFill.bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/Content/bootstrap-datetimepicker.css" />
    <link href="https://gitcdn.github.io/bootstrap-toggle/2.2.2/css/bootstrap-toggle.min.css" rel="stylesheet"> @*https://www.bootstraptoggle.com/*@
    <link href="http://cdn.rawgit.com/davidstutz/bootstrap-multiselect/master/dist/css/bootstrap-multiselect.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/editor.bootstrap.min.css" rel="stylesheet" />
    @Styles.Render("~/Content/css")
    @RenderSection("css", required: false)
</head>
<body>
    <nav class="navbar navbar-default">
        <div class="container-fluid">

            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="@Url.Action("Index", "Dashboard")">

                </a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">

                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Dashboard", "Index", "Dashboard")</li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Data <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Upload Nmf", "Index", "Upload")</li>
                                <li>@Html.ActionLink("Reports", "Index", "Home")</li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">PM Counter <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("5g Parser", "Index", "Ericsson")</li>
                                <li>@Html.ActionLink("Parser", "XMLResult", "Home")</li>
                                <li>@Html.ActionLink("Ericsson Upload", "Index", "EricssonUpload")</li>
                                <li>@Html.ActionLink("Dashboard", "Index", "Multiple")</li>
                            </ul>

                        </li>
                        <li>@Html.ActionLink("Logout", "Logout", "Account")</li>
                    }
                    else
                    {

                        <li>@Html.ActionLink("LogIn", "LogIn", "Account")</li>
                    }
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <img src="~/Images/logo_21.png" style="height: 40px; padding-right: 8px;" />
                    <img src="~/Images/logo3.png" />
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>
    <span style="display:none;" id="status">@(ViewBag.Status)</span>
    <div class="body-content">
        @RenderBody()
    </div>
    <footer>
        <p>
            <span>Copyrights © 2010-@DateTime.Now.Year - deekshatech L</span> <span style="padding-left:8px;"> All Rights Reserved </span>
            <a target="_blank" href="http://www.deekshatech.in" style="padding-left:10px;color:#fff"><span class="glyphicon glyphicon-globe"></span><span style="padding-left:10px">www.deekshatech.in</span></a>
            <a href="mailto:support@deekshatech.in" style="padding-left:10px;color:#fff"><span class="glyphicon glyphicon-envelope"></span><span style="padding-left:10px">support@deekshatech.in</span></a>
        </p>
    </footer>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/galaxy")
    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.1/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap.min.js"></script>
    <script src="https://cdn.datatables.net/autofill/2.3.4/js/dataTables.autoFill.min.js"></script>
    <script src="https://cdn.datatables.net/autofill/2.3.4/js/autoFill.bootstrap.min.js"></script>

    <script type="text/javascript" src="~/scripts/moment.min.js"></script>
    <script type="text/javascript" src="~/scripts/bootstrap-datetimepicker.js"></script>
    <script src="https://gitcdn.github.io/bootstrap-toggle/2.2.2/js/bootstrap-toggle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js"
            integrity="sha256-R4pqcOYV8lt7snxMQO/HSbVCFRPMdrhAFMH+vr9giYI=" crossorigin="anonymous"></script>
    <script src="http://cdn.rawgit.com/davidstutz/bootstrap-multiselect/master/dist/js/bootstrap-multiselect.js"></script>

    <script>
        function ShowOverlay() {
            $("#overlay").show();
            $("#spinner").show();

        }
        function HideOverlay() {
            $("#overlay").hide();
            $("#spinner").hide();
        }
        $(document).ready(function () {
            toastr.options = {
                "closeButton": true,
                "debug": false,
                "newestOnTop": false,
                "progressBar": false,
                "positionClass": "toast-top-center",
                "preventDuplicates": false,
                "onclick": null,
                "showDuration": "300",
                "hideDuration": "1000",
                "timeOut": "5000",
                "extendedTimeOut": "1000",
                "showEasing": "swing",
                "hideEasing": "linear",
                "showMethod": "fadeIn",
                "hideMethod": "fadeOut",
                "preventDuplicates": true,
                "preventOpenDuplicates": true
            };
        });
    </script>
    <script type="text/javascript">
        $(document).ready(() => {
            var statusValue = $("#status").text();
            if (statusValue != null && statusValue != "") {
                if (statusValue == "Duplicate") {
                    toastr.error("Record already exists");
                }
                if (statusValue == "Failed") {
                    toastr.error("Some error occured. Please try again");
                }
                if (statusValue == "Created") {
                    toastr.success("Record has been created");
                }
                if (statusValue == "Updated") {
                    toastr.success("Record has been udpated");
                }

                if (statusValue == "Deleted") {
                    toastr.success("Record has been deleted");
                }
                if (statusValue == "DeleteError") {
                    toastr.success("Record cannot be deleted. Please try again or contact administrator.");
                }
            }
        });
    </script>
    @RenderSection("scripts", required: false)
</body>
</html>

GPSMap/Views/Shared/_Reports.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Scripts.Render("~/bundles/modernizr")

    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" />
    <link href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css" rel="stylesheet" />
    <link href="https://cdn.datatables.net/autofill/2.3.4/css/autoFill.bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="/Content/bootstrap-datetimepicker.css" />
    @Styles.Render("~/Content/css")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="/Dashboard"><img src="~/Images/logo_21.png" /><img src="~/Images/logo3.png" /></a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav" style="float:right;">
                    <li>@Html.ActionLink("5g Parser", "Index", "Ericsson")</li>
                    <li>@Html.ActionLink("Parser", "XMLResult", "Home")</li>
                   
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <footer>
            <hr />
            <p>&copy; @DateTime.Now.Year - Galaxy </p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @*<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet"
              integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
                integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
                crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"
                integrity="sha384-6khuMg9gaYr5AxOqhkVIODVIvm9ynTT5J4V1cfthmT+emCG6yVmEZsRHdxlotUnm"
                crossorigin="anonymous"></script>*@

    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/toastr")
    <script src="//cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.1/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap.min.js"></script>
    <script src="https://cdn.datatables.net/autofill/2.3.4/js/dataTables.autoFill.min.js"></script>
    <script src="https://cdn.datatables.net/autofill/2.3.4/js/autoFill.bootstrap.min.js"></script>
    <script type="text/javascript" src="/scripts/moment.min.js"></script>
    <script type="text/javascript" src="/scripts/bootstrap-datetimepicker.js"></script>
    <script>
        $(document).ready(function () {
            toastr.options = {
                "closeButton": true,
                "debug": false,
                "newestOnTop": false,
                "progressBar": false,
                "positionClass": "toast-top-center",
                "preventDuplicates": false,
                "onclick": null,
                "showDuration": "300",
                "hideDuration": "1000",
                "timeOut": "5000",
                "extendedTimeOut": "1000",
                "showEasing": "swing",
                "hideEasing": "linear",
                "showMethod": "fadeIn",
                "hideMethod": "fadeOut"
            };
        });
    </script>
    @RenderSection("scripts", required: false)
</body>
</html>